// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: health.sql

package service

import (
	"context"
)

const createHealth = `-- name: CreateHealth :one
INSERT INTO health (
    message, 
    service
) 
VALUES (
    $1, 
    $2
)
RETURNING message, service, created_at
`

type CreateHealthParams struct {
	Message string `json:"message"`
	Service string `json:"service"`
}

func (q *Queries) CreateHealth(ctx context.Context, arg CreateHealthParams) (Health, error) {
	row := q.db.QueryRowContext(ctx, createHealth, arg.Message, arg.Service)
	var i Health
	err := row.Scan(&i.Message, &i.Service, &i.CreatedAt)
	return i, err
}
