// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package service

import (
	"time"
)

type Health struct {
	Message   string    `json:"message"`
	Service   string    `json:"service"`
	CreatedAt time.Time `json:"created_at"`
}

type Source struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Url       string    `json:"url"`
	Driver    string    `json:"driver"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
