// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package service

import (
	"context"
)

type Querier interface {
	CreateHealth(ctx context.Context, arg CreateHealthParams) (Health, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	DeleteSource(ctx context.Context, id int32) (Source, error)
	GetSource(ctx context.Context, id int32) (Source, error)
	ListSources(ctx context.Context) ([]Source, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
}

var _ Querier = (*Queries)(nil)
