// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: health.sql

package db

import (
	"context"
)

const insertHealth = `-- name: InsertHealth :one
INSERT INTO health (
    message, 
    service
) 
VALUES (
    $1, 
    $2
)
RETURNING message, service, created_at
`

type InsertHealthParams struct {
	Message string
	Service string
}

func (q *Queries) InsertHealth(ctx context.Context, arg InsertHealthParams) (Health, error) {
	row := q.db.QueryRowContext(ctx, insertHealth, arg.Message, arg.Service)
	var i Health
	err := row.Scan(&i.Message, &i.Service, &i.CreatedAt)
	return i, err
}
